### ISSUE TITLE
supervisor - waiting for queue

### ISSUE THREAD

**Issue by lsv** [michelsalib/BCCResqueBundle#131]
Im having some trouble by running resque from supervisor.

My supervisor configuration

```
[program:app:import_products2]
directory=/home/lsv/dcs_shop
command=php vendor/bcc/resque-bundle/BCC/ResqueBundle/bin/resque
numprocs=1
autostart=true
autorestart=true
startretries=2
environment=ENVIRONMENT='dev',QUEUE='import_products',VERBOSE='1',APP_INCLUDE='/home/lsv/dcs_shop/app/bootstrap.php.cache'
user=lsv
stderr_logfile=/var/log/dcs/import_products.err.log
stdout_logfile=/var/log/dcs/import_products.log
```

The error log file is empty, and the stdout logfile is just full of

```
[info] [18:25:31 2015-09-17] Checking import_products for jobs
[info] [18:25:31 2015-09-17] Sleeping for 5
[info] [18:25:36 2015-09-17] Checking import_products for jobs
[info] [18:25:36 2015-09-17] Sleeping for 5
[info] [18:25:41 2015-09-17] Checking import_products for jobs
[info] [18:25:41 2015-09-17] Sleeping for 5
[info] [18:25:46 2015-09-17] Checking import_products for jobs
[info] [18:25:46 2015-09-17] Sleeping for 5
```

Though I have 17000 jobs to run

If I run ```php app/console bcc:resque:worker-start import_products``` from the console it begins to process my jobs without problems.

So what is missing in the supervisor configuration?

I can see that "PREFIX" is missing, but Im not sure what I should add here?

My job entity

```php
<?php
namespace Dcs\ImporterBundle\Jobs;

use BCC\ResqueBundle\ContainerAwareJob;
use Dcs\ProductBundle\Entity\Product;

class ImportProductJob extends ContainerAwareJob
{

    public function __construct()
    {
        $this->queue = 'import_products';
    }

    public function run($args)
    {
        $ret = $this->getContainer()->get('dcs_importerbundle.importer.productimport')->importProduct(unserialize($args['data']), null, true);
        if ($ret instanceof Product) {
            return true;
        }

        return false;
    }
}
```

**Comment by byhoratiss** [comment]
Did you try to use the full path of PHP handler? Like the example from https://github.com/michelsalib/BCCResqueBundle#manage-production-workers-with-supervisord

And simplyfing the alias of the program using underscore, to avoid problem when grouping.

Something like:
```
[program:app_import_products2]
directory=/home/lsv/dcs_shop/
command=/usr/bin/php /home/lsv/dcs_shop/vendor/bcc/resque-bundle/BCC/ResqueBundle/bin/resque
```

**Comment by lsv** [comment]
I finally got it work

```
[program:import_products]
directory=/home/lsv/dcs
command=php vendor/bcc/resque-bundle/BCC/ResqueBundle/bin/resque
user=scandesigns
environment=REDIS_BACKEND='localhost:6379',REDIS_BACKEND_DB='1',ENVIRONMENT='prod',QUEUE='import_products',PREFIX='dcs',VERBOSE='1',APP_INCLUDE='/home/lsv/dcs/app/bootstrap.php.cache'
autostart=true
autorestart=true
startretries=3
stderr_logfile=/var/log/dcs/import_products.err.log
stdout_logfile=/var/log/dcs/import_products.log
```

Though there is one thing that does not work properly - If I want to have multiple workers on, I tried to add COUNT to environment, but if I added 3 here, supervisor would start 6 workers, but only 3 of them where supervised, so restart supervisor a few times and you would have many workers.

So instead I just added multiple lines in my supervisor configuration, and then it works perfect.

**Comment by danhunsaker** [comment]
That bug is a known bug.  PHP-Resque uses forking to start COUNT workers, then the parent process closes, leaving supervisord to think the process never actually started, so it starts it again.  There is a patch waiting to be reviewed which causes the parent process to stick around and manage the workers it spawned (even respawning them when they die, among other things), but unless/until it gets merged in, you have to use `COUNT=1` (the default when COUNT isn't supplied at all), and have supervisord start the correct number of workers itself.
