### ISSUE TITLE
Container Aware Job error

### ISSUE THREAD

**Issue by shwetanka** [michelsalib/BCCResqueBundle#4]
I'm just making my job class extending ContainerAwareJob as shown in the readme section. I'm getting the following error.
Undefined index: kernel.root_dir in /home/shwetanka/practo/pvr/vendor/bundles/BCC/ResqueBundle/ContainerAwareJob.php line 40

I'm using Symfony2.0.x. Is it because of this or some other issue?

**Comment by alexis2209** [comment]
Hi, 

I have the same error : Notice: Undefined index: kernel.root_dir
It's just when I extends my command width ContainerAwareJob
the error comme in $finder->name('*Kernel.php')->depth(0)->in($this->args['kernel.root_dir']);
$this->args is empty ... 

Can you help me ?

Thank you very mutch, and sorry for my ban english

**Comment by razvan379** [comment]
I have the same problem when making call to $this->getContainer();

**Comment by razvan379** [comment]
There is a hack:
In controller
$kernel = $this->get('kernel');
$rootDir = $kernel->getRootDir();
$args = array(
     "some_arg" => "",
     "kernel.root_dir" => $rootDir
)

and in MyJob class inside run function call parent::setKernelOptions($args); first
