### ISSUE TITLE
Controlling workers with supervisord

### ISSUE THREAD

**Issue by t3chn0r** [michelsalib/BCCResqueBundle#79]
I'm still having issues trying to manage these workers with supervisor. I tried both configurations:

```
[program:acme.com.resqueworker]
command=php app/console --env=dev bcc:resque:worker-start '*' --foreground
directory=/var/www/acme.com
user=www-data
autostart=true
autorestart=true
```

and...

```
[program:acme.com.resqueworker]
command = /usr/bin/php /var/www/acme.com/vendor/bcc/resque-bundle/BCC/ResqueBundle/bin/resque
user = myusername
environment = APP_INCLUDE='/var/www/acme.com/vendor/autoload.php',VERBOSE='1',QUEUE='*'
```

After I start the service (supervisorctl start acme.com.resqueworker) I can see these processes running:

```
www-data  4917     1  0 09:46 ?        00:00:00 sh -c php  /var/www/acme.com/app/../vendor/chrisboulton/php-resque/resque.php
www-data  4918  4917  0 09:46 ?        00:00:00 php /var/www/acme.com/app/../vendor/chrisboulton/php-resque/resque.php
```

Now, when I try to manually shutdown the service I see the following:

```
root@harrenhal:/etc/supervisor/conf.d# supervisorctl stop acme.com.resqueworker
acme.com.resqueworker: stopped
root@harrenhal:/etc/supervisor/conf.d# supervisorctl stop acme.com.resqueworker
acme.com.resqueworker: ERROR (not running)
```

I assume that now the worker is not running anymore as the first command notifies a successful stop and the second one says that it's not running anymore... But if I check the processes again I can still see them running:

```
www-data  4917     1  0 09:46 ?        00:00:00 sh -c php  /var/www/acme.com/app/../vendor/chrisboulton/php-resque/resque.php
www-data  4918  4917  0 09:46 ?        00:00:00 php /var/www/acme.com/app/../vendor/chrisboulton/php-resque/resque.php
```

So it appears supervisor can start these background processes but for some reason it can't stop them.

Any ideas? If anyone else using supervisor and working ok?

Regards

**Comment by PATROMO** [comment]
The solution is `stopasgroup=true`:

`If true, the flag causes supervisor to send the stop signal to the whole process group and implies killasgroup is true. This is useful for programs, such as Flask in debug mode, that do not propagate stop signals to their children, leaving them orphaned.`
